feat(switcher): add disabled property
antvis/S2 pull request #1217
Opened 2022-03-29 04:02 UTC by Esorakouki

### 👀 PR includes

✨ Feature

- add disabled property

- add css to center disabled popover Button
![image](https://user-images.githubusercontent.com/15276351/160530193-8df08b42-c969-4ca4-ba83-c4c046762ba5.png)

2022-03-29 07:59 UTC, stone-lyl submitted a review, later dismissed

2022-03-29 09:00 UTC, lijinke666 requested changes
麻烦补充一下 @Esorakouki 单测和文档

2022-04-19 05:06 UTC, wjgogogo approved these changes

2022-04-19 05:07 UTC, lijinke666 approved these changes

2022-04-19 05:07 UTC, merged

2022-04-22 10:14 UTC, lijinke666 commented
:tada: This PR is included in version @antv/s2-react-v1.14.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@antv/s2-react/v/1.14.0)
- [GitHub release](https://github.com/antvis/S2/releases/tag/%40antv/s2-react-v1.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-25 08:09 UTC, lijinke666 commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/antvis/S2/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: