Feat data cell link
antvis/S2 pull request #2102
Opened 2023-02-28 15:23 UTC by wbbhacker

### 👀 PR includes

✨ Feature

- [x] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [ ] Solve the issue and close #0

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌   透视表values不支持 标记为链接样式   | ✅    透视表values支持 标记为链接样式 |

### 🔗 Related issue link

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

2023-03-02 02:09 UTC, lcx-seima commented
👏🏻 感谢贡献

2023-03-02 02:25 UTC, lcx-seima reviewed
再考虑下继承调用方式？
另外，需要增加一下单测哦

2023-03-02 02:25 UTC, lcx-seima commented on packages/s2-core/src/cell/data-cell.ts
> +    this.drawLinkFieldShapeOwn();
这个子类方法为什么不复写 drawLinkFieldShape 名？是因为看到 table-data-cell extends data-cell 吗。

感觉可以这样？
table-data-cell 里 drawLinkFieldShape 移动到 data-cell 来，这样 table-data-cell 和 data-cell 都共享 drawLinkFieldShape 逻辑了。
唯一不同的是 linkField 的样式。

可以新增一个 getLinkFieldStyle：
- dataCell 直接调用，返回 `const { linkTextFill } = this.getTextStyle()`
- tableDataCell 复写方法，返回 `rowCell.text.linkTextFill`

2023-03-02 02:28 UTC, lijinke666 requested changes

2023-03-02 02:28 UTC, lijinke666 commented on packages/s2-core/src/cell/data-cell.ts
> +    super.drawLinkFieldShape(isLinkField, linkTextFill);
不要直接复制 `rowCell` 的方法吧, 可以把原本的 `drawLinkFieldShape` 移到 `baseCell` 中, `rowCell`, `dataCell`, `colCell` 都可以用

2023-03-02 02:29 UTC, lijinke666 commented
请补充一个 demo 和相关单测, 谢谢

2023-03-02 02:49 UTC, wbbhacker commented on packages/s2-core/src/cell/data-cell.ts
> +    super.drawLinkFieldShape(isLinkField, linkTextFill);
好的

2023-03-02 02:49 UTC, wbbhacker commented on packages/s2-core/src/cell/data-cell.ts
> +    this.drawLinkFieldShapeOwn();
好的

2023-03-10 10:02 UTC, lijinke666 commented on packages/s2-react/playground/index.html
> +    <!-- s2-core  data-cell-spec.ts 中 Link Shape Tests 数据demo -->
新增 本地 demo 为什么要通过这种方式, 而不是在 index.tsx 加一个组件?

2023-03-10 10:02 UTC, lijinke666 commented on packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
> +      "linkTextFill": "#326EF4",
麻烦新增一个官网 Demo

2023-03-13 05:24 UTC, wbbhacker commented on packages/s2-react/playground/data-cell-demo.tsx
> +import { PivotSheet } from '@antv/s2';
好的

2023-03-13 08:00 UTC, lijinke666 commented on packages/s2-core/src/cell/data-cell.ts
> +import { checkIsLinkField } from '../utils/interaction/link-field';
这个是不是没用到

2023-03-13 09:20 UTC, wbbhacker commented on packages/s2-core/src/cell/data-cell.ts
> +import { checkIsLinkField } from '../utils/interaction/link-field';
是的，没用到

2023-03-15 09:13 UTC, lijinke666 approved these changes

2023-03-22 08:05 UTC, merged

2023-03-24 09:16 UTC, lijinke666 commented
:tada: This PR is included in version @antv/s2-v1.44.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@antv/s2/v/1.44.0)
- [GitHub release](https://github.com/antvis/S2/releases/tag/%40antv/s2-v1.44.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-24 09:18 UTC, lijinke666 commented
:tada: This PR is included in version @antv/s2-react-v1.38.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@antv/s2-react/v/1.38.0)
- [GitHub release](https://github.com/antvis/S2/releases/tag/%40antv/s2-react-v1.38.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-04-28 10:49 UTC, lijinke666 commented
:tada: This PR is included in version @antv/s2-v2.0.0-next.7 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@antv/s2/v/2.0.0-next.7)
- [GitHub release](https://github.com/antvis/S2/releases/tag/%40antv/s2-v2.0.0-next.7)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-04-28 10:55 UTC, lijinke666 commented
:tada: This PR is included in version @antv/s2-react-v2.0.0-next.6 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@antv/s2-react/v/2.0.0-next.6)
- [GitHub release](https://github.com/antvis/S2/releases/tag/%40antv/s2-react-v2.0.0-next.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: