feat(table filter): add custom filter function feat
antvis/S2 pull request #894
Opened 2021-12-14 09:06 UTC by YardWill

### 👀 PR includes

✨ Feature

- [x] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [ ] Solve the issue and close #0

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description

add custom filter function feat

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔗 Related issue link

### 🔍 Self Check before Merge

- [ ] Add or update relevant Docs.
- [ ] Add or update relevant Demos.
- [ ] Add or update relevant TypeScript definitions.

2021-12-15 02:48 UTC, lijinke666 commented on packages/s2-core/src/common/interface/basic.ts
> +  filterFunction?: (row: DataType) => boolean;
filterFunction 这个名字 太抽象了吧...

就叫 `filter` ? 或者 `customFilter`

2021-12-23 11:23 UTC, serializedowen requested changes

2021-12-23 11:23 UTC, serializedowen commented on packages/s2-core/src/data-set/table-data-set.ts
> +        ...filter(this.getMovableRows(), customFilter || defaultFilterFunc),
filteredValues and customFilter are supposed to be independent, with neither taking precedence over each other

2021-12-24 02:47 UTC, zxc0328 approved these changes
LG

2021-12-24 02:49 UTC, serializedowen approved these changes

2021-12-24 02:51 UTC, merged

2021-12-24 03:47 UTC, lijinke666 commented
:tada: This PR is included in version @antv/s2-v1.4.0-alpha.4 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@antv/s2/v/1.4.0-alpha.4)
- [GitHub release](https://github.com/antvis/S2/releases/tag/%40antv/s2-v1.4.0-alpha.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-24 09:48 UTC, lijinke666 commented
:tada: This PR is included in version @antv/s2-v1.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@antv/s2/v/1.4.0)
- [GitHub release](https://github.com/antvis/S2/releases/tag/%40antv/s2-v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: