Fix adaptive
antvis/S2 pull request #940
Opened 2021-12-23 11:39 UTC by stone-lyl

### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [X] Solve the issue and close #901 

🔧 Chore

- [ ] Test case
- [X] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description
1. fix: 修复当数据为空时，this.displayData[query.rowIndex] 为undefined，无法获取 [query.col]
2. feat: 在 sheetType 为 pivot 或者 gridAnalysis 时，新增 adaptiveRef 属性，让表格可自适应外部元素宽高。
3. docs: adaptiveRef 属性相关文档补充

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |
|![image](https://user-images.githubusercontent.com/20497176/147234644-8738107c-ad3f-4eb6-9e92-d39cee9114f1.png)|![image](https://user-images.githubusercontent.com/20497176/147235191-a11aa7ab-2550-45da-844b-700e499fafc5.png)|

### 🔗 Related issue link
https://github.com/antvis/S2/issues/901

### 🔍 Self Check before Merge

- [X] Add or update relevant Docs.
- [ ] Add or update relevant Demos.
- [X] Add or update relevant TypeScript definitions.

2021-12-23 12:16 UTC, lijinke666 commented on s2-site/docs/manual/advanced/adaptive.zh.md
> +| adaptive        | 是否开启自适应        | `boolean`               | -      |      |
这个 `api` 建议这么设计

```ts
type Adaptive = boolean | { width?: boolean, height?: boolean, container: HTMLElement }
```
// 配置为 boolean 值时, 容器默认为内部的 container, 宽高都自适应
```tsx
<SheetComponent adaptive={true} />
<SheetComponent adaptive={false} />
```

// 配置为 object 时, 就代表自适应开启, 可具体配置只 自适应宽度, 还是高度, 还是宽高都自适应, 然后可以自己指定容器

```tsx
const containerRef = useRef<HTMLDivElement>();

<div ref={containerRef} />

<SheetComponent adaptive={{
  width: true,
  height: false,
  container: containerRef.current
}} />
```

2021-12-23 12:22 UTC, lijinke666 commented
pr 改下标题

2021-12-23 12:29 UTC, stone-lyl commented on s2-site/docs/manual/advanced/adaptive.zh.md
> +| adaptive        | 是否开启自适应        | `boolean`               | -      |      |
采纳建议 ❀

2021-12-24 02:17 UTC, zxc0328 requested changes

2021-12-24 02:17 UTC, zxc0328 commented on packages/s2-core/src/data-set/table-data-set.ts
> +    return this.displayData[query.rowIndex]?.[query.col];
这个最好不要这么改哈。因为这样的话，一些 rowIndex 计算错误的问题就没法暴露出来了。还是要从源头上去避免 getCellData 里面 rowIndex 不正确的问题，

2021-12-24 02:23 UTC, zxc0328 commented on packages/s2-core/src/data-set/table-data-set.ts
> +    return this.displayData[query.rowIndex]?.[query.col];
宽度和高度为 0 的时候明细表报错的问题，我们这边可以单独修，这个 PR 可以先解决 adaptive 属性的问题

2021-12-24 06:56 UTC, zxc0328 commented on packages/s2-core/src/data-set/table-data-set.ts
> +    return this.displayData[query.rowIndex]?.[query.col];
https://github.com/antvis/S2/pull/947 这个 PR 改了

2021-12-24 07:33 UTC, stone-lyl commented on packages/s2-core/src/data-set/table-data-set.ts
> +    return this.displayData[query.rowIndex]?.[query.col];
但是这里一旦无法通过 `this.displayData[query.rowIndex]` 找到数据，就会直接跑错给用户，在界面上报错。

2021-12-24 07:33 UTC, stone-lyl commented on packages/s2-core/src/data-set/table-data-set.ts
> +    return this.displayData[query.rowIndex]?.[query.col];
我在你的PR下评论了，我这边暂不处理了。

2021-12-24 08:03 UTC, lijinke666 commented on packages/s2-react/src/components/sheets/interface.ts
> +export type AdaptiveContainer = HTMLDivElement | HTMLElement;
直接 HTMLElement 即可，HTMLDIV是它的子集

2021-12-24 08:03 UTC, lijinke666 commented on packages/s2-react/src/components/sheets/interface.ts
> +      container: () => AdaptiveContainer;
叫 getContainer好一点

2021-12-24 08:56 UTC, zxc0328 approved these changes

2021-12-24 09:17 UTC, xingwanying commented on packages/s2-react/__tests__/spreadsheet/adaptive-spec.tsx
> +  // https://github.com/antvis/S2/issues/901
这个test建议挪到bug下面方便统一管理

2021-12-24 09:32 UTC, merged

2021-12-24 09:52 UTC, lijinke666 commented
:tada: This PR is included in version @antv/s2-react-v1.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@antv/s2-react/v/1.4.0)
- [GitHub release](https://github.com/antvis/S2/releases/tag/%40antv/s2-react-v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: